spring:
#rabbitMQ消息队列服务配置
  rabbitmq:
    host: 172.18.10.131
    virtualHost: test
    username: pjadmin
    password: Purking0326
#日志配置
logging:
  level:
    root: debug
#数据库数据源
druid:
  url: jdbc:mysql://47.98.40.54:3306/gps?characterEncoding=UTF-8
  username: mysql
  password: mysql
  initial-size: 1
  min-idle: 1
  max-active: 50
  test-on-borrow: true
  driver: com.mysql.jdbc.Driver
#---------------------------rest访问 相关---------------------------------    
rest: 
  pcms: 
    url: http://172.18.10.82:9009/pcms-web-dev-1/pcms-web
  pcms-query:
    url: http://10.253.41.29:8080/pcms-web-query
  #赛格上传gps数据地址
  seg:
    url: http://218.17.3.228:8000/pjjrserver/gps/addAddress

#---------------------------赛格上传数据MD5 key值---------------------------------   
segUpload:
  md5Key: PUJINJINRONGGPS2018
  successCode: 888888
 
    
#---------------------------定时任务 相关---------------------------------      
#调度器是否启用
schedul:
  start: true
  #库存盘点时间
  takeStock: 
    cronTime: 0 0 3 1 * ?
  #自动提交时间
  autoCommit: 
    cronTime: 0 0 3 2 * ?
  #自动上传数据到赛格，凌晨2点执行
  autoUploadToSeg:
    cronTime: 0 00 2 ? * *
  #一次性上传所有数据到赛格
  autoAllDataUploadToSeg:
    cronTime: 0 15 16 6 3 ?   
    
#---------------------------文件 相关---------------------------------          
#excel下载，临时文件保存目录
file: 
  excelPath: temp   
#---------------------------excel校验开关 相关---------------------------------            
#excel导入gps编码规则校验开关(true:启用gps编码规则校验；false：关闭gps编码规则校验)
excel: 
  valid:
    switch: true
#重复gps编码校验开关(true:入库时，启用gps编码重复性校验；false：入库时，关闭gps编码重复性校验)
gps:
  duplicated:
    switch: true
    
jdbc_driverClassName_master: com.mysql.jdbc.Driver
jdbc_url_master: jdbc:mysql://172.18.10.145:3306/test?characterEncoding=UTF-8
jdbc_username_master: root
jdbc_password_master: Good1235

